apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-editor-configurations
  namespace: devspaces
  labels:
    app.kubernetes.io/component: workspaces-config
    app.kubernetes.io/part-of: che.eclipse.org
data:
  settings.json: |
    {
      "workbench.startupEditor": "readme",
      "workbench.editorAssociations": {
        "**/README.md": "vscode.markdown.preview.editor"
      },
      "ansible.python.interpreterPath": "/opt/ansible/bin/python",
      "ansible.ansible.path": "/usr/local/bin/ansible",
      "ansible.validation.enabled": true,
      "ansible.validation.lint.enabled": true,
      "ansible.validation.lint.path": "/usr/local/bin/ansible-lint",
      "ansible.executionEnvironment.enabled": false,
      "files.associations": {
        "**/playbooks/**/*.yml": "ansible",
        "**/roles/**/*.yml": "ansible",
        "**/inventory/**/*.yml": "yaml"
      },
      "redhat.telemetry.enabled": false
    }
  extensions.json: |
    {
      "recommendations": [
        "redhat.ansible",
        "redhat.vscode-yaml",
        "ms-kubernetes-tools.vscode-kubernetes-tools",
        "redhat.vscode-openshift-connector"
      ]
    }