apiVersion: v1
kind: ConfigMap
metadata:
  name: vscode-editor-configurations
  namespace: devspaces
  labels:
    app.kubernetes.io/component: workspaces-config
    app.kubernetes.io/part-of: che.eclipse.org
data:
  settings.json: |
    {
      "workbench.startupEditor": "readme"
    }