apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-registry-pvc
  labels:
    app: local-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      